version: 2

sources:
  - name: staging
    description: a clone of a Postgres 
    database: stores_data
    schema: public
    tables:
      - name: customer
        description: raw data for customers

      - name: order
        description: Table containing order details with information about each order.

      - name: order_detail
        description: Table containing detailed information about products within each order, including sales metrics and cost details.
       

      - name: product
        description: raw data for customers
      
      - name: returned
        description: raw data about returned orders
        
      - name: shipping
        description: Table containing details about the shipping process for each order, including shipment dates and destinations.